name: Java CI with Maven

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Display Maven dependencies
        run: mvn dependency:tree
        # Optionally, you can specify the path to your pom.xml file if it's not in the root directory:
        # run: mvn dependency:tree --file path/to/pom.xml
