name: Check POM XML

on:
  push:
    branches:
      - main

jobs:
  check:
    name: Check POM XML
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: 8

      - name: Validate POM XML (Java 8)
        run: mvn validate --file pom.xml -Pjava8

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11

      - name: Validate POM XML (Java 11)
        run: mvn validate --file pom.xml -Pjava11

      # Repeat the setup and validation steps for Java 14 and 17 if needed
