name: Java Versions

on:
  push:
    branches:
      - main

jobs:
  check:
    name: Java Versions
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: 8
          distribution: 'adopt'

      - name: Validate POM XML (Java 8)
        run: mvn validate --file pom.xml -Pjava8

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'adopt'

      - name: Validate POM XML (Java 11)
        run: mvn validate --file pom.xml -Pjava11

      - name: Set up JDK 14
        uses: actions/setup-java@v2
        with:
          java-version: 14
          distribution: 'adopt'

      - name: Validate POM XML (Java 14)
        run: mvn validate --file pom.xml -Pjava14

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'adopt'

      - name: Validate POM XML (Java 17)
        run: mvn validate --file pom.xml -Pjava17

      # Repeat the setup and validation steps for Java 14 and 17 if needed
